version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  site:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env